#!/bin/sh

#set -e
echo "Starting hook $0: set grub" 
# Make sure we're not working on the root directory
if [ -z "$TARGET" -o "$TARGET" = "/" ]; then
    echo "Invalid target directory '$TARGET', aborting." 1>&2
    exit 1
fi

if [ "$(mountpoint -d /)" = "$(mountpoint -d "$TARGET")" ]; then
    echo "The target directory seems to be the root dir, aborting."  1>&2
    exit 1
fi

# Fix the console information for xen-pvm mode
if [ "$HYPERVISOR" = "xen-pvm" ]; then
    echo "xen-pvm hypervisor detected, preparing for grub"
    mkdir -p "$TARGET/boot/grub"
    cat <<EOF >"$TARGET/boot/grub/menu.lst"
default         0
timeout         5
color cyan/blue white/blue

title           Debian GNU/Linux, default kernel
root            (hd0,0)
kernel          /vmlinuz root=/dev/xvda ro console=hvc0
initrd          /initrd.img

title           Debian GNU/Linux, default kernel (single-user mode)
root            (hd0,0)
kernel          /vmlinuz root=/dev/xvda ro single
initrd          /initrd.img
EOF

fi
echo "Finishing hook $0" 
exit 0
