#!/bin/bash
#
# Install packages
#
# Do not include packages in EXTRA_PKGS because it will cause error of debootstrap.
echo "Starting hook 01-packages: install additional packages"


. common.sh

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

CLEANUP=( )

trap cleanup EXIT

set -e

if [ -e $TARGET/media/cdrom ]; then
	mount -o bind /media/sci $TARGET/media/cdrom
	CLEANUP+=("umount $TARGET/media/cdrom")
fi

LANG=C

echo Updating package sources
chroot "$TARGET" apt-get update

echo Installing packages
chroot "$TARGET" apt-get -y --force-yes install puppet openssh-client openssh-server lsb-release

if [ "$OS_VARIANT" = "sci" ]; then
 echo Installing packages for SCI
 echo START=no >"$TARGET/etc/default/puppetmaster"
 echo N|chroot "$TARGET" apt-get -y --force-yes install puppetmaster
 echo exit >"$TARGET/etc/default/openbsd-inetd"
 echo N|chroot "$TARGET" apt-get -y --force-yes install approx
 echo N|chroot "$TARGET" apt-get -y --force-yes install openbsd-inetd
 echo "9999             stream  tcp     nowait  approx  /usr/sbin/approx /usr/sbin/approx" >> $TARGET/etc/inetd.conf
 chroot "$TARGET" apt-get -y --force-yes install ipcalc git rng-utils
 rm "$TARGET/etc/default/openbsd-inetd"
fi

echo "Finishing hook 01-packages"
# execute cleanups
cleanup
trap - EXIT
