#!/bin/bash
#
# Configuring puppet
echo "Starting hook 02-puppet: add puppet agent"

. common.sh

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

# enable puppet autostart
cat <<EOF >"$TARGET/etc/default/puppet"
# Defaults for puppet - sourced by /etc/init.d/puppet

# Start puppet on boot?
START=yes

# Startup options
DAEMON_OPTS=""
EOF

test "$OS_VARIANT" = "wheezy" -o "$OS_VARIANT" = "squeeze" || exit 0

## Allow plugins and facts syncing for puppet
sed -i '/\[main\]/ a\pluginsync = true' $TARGET/etc/puppet/puppet.conf

echo "Finishing hook 02-puppet"
