#!/bin/bash
echo "Starting hook copy-root-password"

# Make sure we're not working on the root directory
if [ -z "$TARGET" -o "$TARGET" = "/" ]; then
    echo "Invalid target directory '$TARGET', aborting." 1>&2
    exit 1
fi

if [ "$(mountpoint -d /)" = "$(mountpoint -d "$TARGET")" ]; then
    echo "The target directory seems to be the root dir, aborting."  1>&2
    exit 1
fi

echo "Copy root password from node"
sed -i "1i`cat /etc/shadow|grep root`" "$TARGET/etc/shadow"
sed -i "2d" "$TARGET/etc/shadow"

echo "Finishing hook copy-root-password"
exit 0
