#!/bin/sh
#
echo "Starting hook dhclient: set send-hostname for debian-squeeze"

test "$OS_VARIANT" != "squeeze" && exit 0

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

echo Setting dhclient send-hostname
sed -i "s/#send host-name.*/send host-name \"$(echo $INSTANCE_NAME|cut -d. -f1)\"\;/" $TARGET/etc/dhcp/dhclient.conf

echo "Finishing hook dhclient"
exit 0
