#!/bin/bash
#
# Copy sci.conf for puppet reference

set -e

test "$OS_VARIANT" = "sci" || exit 0

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

echo Set puppet reports cleaning
echo "13 3    * * *   root    find /var/lib/puppet/reports -type f -ctime +30|xargs rm -fr" >> $TARGET/etc/cron.d/clean-puppet-reports

exit 0
