#!/bin/bash
#
echo "Starting hook resolv: Set up hosts and resolv.conf for LAN"

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

echo Setting up hosts and hostname

if [[ "$OS_VARIANT" == "sci" ]]; then
	grep ^search /etc/resolv.conf >"$TARGET/etc/resolv.conf"
	echo "nameserver 127.0.0.1" >>"$TARGET/etc/resolv.conf"
	exit 0
fi

hostname=`echo $INSTANCE_NAME|cut -d. -f1`
# set fqnd from resolv conf if INSTANCE_NAME don't contain it.
if (echo $INSTANCE_NAME|grep -q "\.") then
    fqdn="$INSTANCE_NAME"
else
    domain=`grep search /etc/resolv.conf|cut -d' ' -f2`
    fqdn="$INSTANCE_NAME.$domain"
fi 

cat <<EOF >"$TARGET/etc/hosts"
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

127.0.1.1 $fqdn $hostname
EOF

echo $hostname > "$TARGET/etc/hostname"

. /etc/sci/sci.conf

test -z "$SCI_LAN_IP" && exit 0
echo Setting up resolv.conf for LAN

grep ^search /etc/resolv.conf >"$TARGET/etc/resolv.conf"
echo "nameserver $SCI_LAN_IP" >>"$TARGET/etc/resolv.conf"


echo "Finishing hook resolv"
exit 0
