#!/bin/bash
#
# Copy root ssh authorized keys to sci

set -e

test "$OS_VARIANT" = "sci" || exit 0

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

echo Copy root ssh authorized keys to sci
mkdir -p "$TARGET/root/.ssh"
chmod 700 "$TARGET/root/.ssh"
cp /root/.ssh/authorized_keys "$TARGET/root/.ssh"

exit 0
