#!/bin/bash
#
echo "Starting hook sci-media: Copy SCI CD-ROM packages repository for approx"

test "$OS_VARIANT" = "sci" || exit 0

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

echo Copying SCI CD-ROM repository
mkdir -p "$TARGET/media/sci"
cp -r /media/sci/dists /media/sci/pool "$TARGET/media/sci"

echo "Finishing hook sci-media"
exit 0
