#!/bin/bash
#
echo "Starting hook sci-conf: Copy sci.conf for puppet reference"

test "$OS_VARIANT" = "sci" || exit 0

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

echo Copying sci.conf
mkdir -p "$TARGET/etc/sci"
cp /etc/sci/sci.conf "$TARGET/etc/sci/sci.conf"

echo "Finishing hook sci-conf"
exit 0
