#!/bin/bash
#
echo "Starting hook z_puppet-enable: Enable puppet for modern debians"

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

test "$OS_VARIANT" = "wheezy" -o "$OS_VARIANT" = "squeeze" && exit 0

echo Enabling puppet agent
chroot "$TARGET" /usr/bin/puppet agent --enable
echo Killing puppet agent
chroot "$TARGET" /bin/kill -9 `cat $TARGET/run/puppet/agent.pid`

echo "Finishing hook z_puppet-enable"
exit 0

