#!/bin/bash
#
echo "Starting hook z-ssh-enable-root: Enable root ssh access with password"

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

test "$OS_VARIANT" = "wheezy" -o "$OS_VARIANT" = "squeeze" && exit 0

echo set ssh PermitRootLogin yes
sed -i 's/#PermitRootLogin without-password/PermitRootLogin yes/' $TARGET/etc/ssh/sshd_config
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' $TARGET/etc/ssh/sshd_config

echo "Finishing hook z-ssh-enable-root"
exit 0

